from enum import Enum

from BaseClasses import Item, ItemClassification

class WildfrostItem(Item): #TODO
    game: str = "Wildfrost"


class ItemType(Enum):
    Unknown = 0, # Fallback value, should not be used
    Building = 1,
    Charm = 2,
    Unit = 3,
    Item = 4,
    Bell = 5,
    MapEvent = 6,
    Tribe = 7,
    TrapBoon = 8

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
building_list = {
    "Pet House":            (ItemType.Building, ItemClassification.progression, 0  ),
    "Inventor's Hut":       (ItemType.Building, ItemClassification.progression, 1  ),
    "Icebreaker Cabin":     (ItemType.Building, ItemClassification.progression, 2  ),
    "Hot Spring":           (ItemType.Building, ItemClassification.progression, 3  ),
    "Frostoscope":          (ItemType.Building, ItemClassification.useful,      4  ),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
charm_list = {
    "Acorn Charm":          (ItemType.Charm,    ItemClassification.useful,      0 ,     ["Snow"]),
    "Balance Charm":        (ItemType.Charm,    ItemClassification.useful,      1  ),
    "Battle Charm":         (ItemType.Charm,    ItemClassification.useful,      2  ),
    "Beetle Charm":         (ItemType.Charm,    ItemClassification.useful,      3  ),
    "Bite Charm":           (ItemType.Charm,    ItemClassification.useful,      4 ,     ["Shade"]),
    "Bling Charm":          (ItemType.Charm,    ItemClassification.useful,      5  ),
    "Block Charm":          (ItemType.Charm,    ItemClassification.useful,      6  ),
    "Bom Charm":            (ItemType.Charm,    ItemClassification.useful,      7 ,     ["Clunk"]),
    "Bombskull Charm":      (ItemType.Charm,    ItemClassification.useful,      8  ),
    "Boonfire Charm":       (ItemType.Charm,    ItemClassification.useful,      9 ,     ["Shade"]),
    "Cake Charm":           (ItemType.Charm,    ItemClassification.useful,      10 ),
    "Chuckle Charm":        (ItemType.Charm,    ItemClassification.useful,      11 ),
    "Cloudberry Charm":     (ItemType.Charm,    ItemClassification.useful,      12 ),
    "Critical Charm":       (ItemType.Charm,    ItemClassification.useful,      13 ),
    "Durian Charm":         (ItemType.Charm,    ItemClassification.useful,      14 ),
    "Fidget Charm":         (ItemType.Charm,    ItemClassification.useful,      15,     ["Clunk"]),
    "Flameblade Charm":     (ItemType.Charm,    ItemClassification.useful,      16,     ["Shade"]),
    "Frenzy Charm":         (ItemType.Charm,    ItemClassification.useful,      17 ),
    "Frog Charm":           (ItemType.Charm,    ItemClassification.useful,      18 ),
    "Frosthand Charm":      (ItemType.Charm,    ItemClassification.useful,      19 ),
    "Frozen Heart Charm":   (ItemType.Charm,    ItemClassification.useful,      20 ),
    "Gear Charm":           (ItemType.Charm,    ItemClassification.useful,      21,     ["Clunk"]),
    "Gnome Charm":          (ItemType.Charm,    ItemClassification.useful,      22 ),
    "Goat Charm":           (ItemType.Charm,    ItemClassification.useful,      23 ),
    "Greed Charm":          (ItemType.Charm,    ItemClassification.useful,      24 ),
    "Heart Charm":          (ItemType.Charm,    ItemClassification.useful,      25 ),
    "Hog Charm":            (ItemType.Charm,    ItemClassification.useful,      26 ),
    "Hook Charm":           (ItemType.Charm,    ItemClassification.useful,      27 ),
    "Jewelberry Charm":     (ItemType.Charm,    ItemClassification.useful,      28,     ["Snow"]),
    "Jimbo Charm":          (ItemType.Charm,    ItemClassification.useful,      29 ),
    "Lamb Charm":           (ItemType.Charm,    ItemClassification.useful,      30,     ["Shade"]),
    "Lumin Charm":          (ItemType.Charm,    ItemClassification.useful,      31 ),
    "Mime Charm":           (ItemType.Charm,    ItemClassification.useful,      32,     ["Shade"]),
    "Moko Charm":           (ItemType.Charm,    ItemClassification.useful,      33 ),
    "Molten Egg Charm":     (ItemType.Charm,    ItemClassification.useful,      34 ),
    "Moose Charm":          (ItemType.Charm,    ItemClassification.useful,      35 ),
    "Muncher Charm":        (ItemType.Charm,    ItemClassification.useful,      36 ),
    "Noomlin Charm":        (ItemType.Charm,    ItemClassification.useful,      37 ),
    "Nourish Charm":        (ItemType.Charm,    ItemClassification.useful,      38 ),
    "Pengu Charm":          (ItemType.Charm,    ItemClassification.useful,      39 ),
    "Peppernut Charm":      (ItemType.Charm,    ItemClassification.useful,      40,     ["Snow"]),
    "Pinch Charm":          (ItemType.Charm,    ItemClassification.useful,      41 ),
    "Pomegranate Charm":    (ItemType.Charm,    ItemClassification.useful,      42 ),
    "Punchfist Charm":      (ItemType.Charm,    ItemClassification.useful,      43 ),
    "Raspberry Charm":      (ItemType.Charm,    ItemClassification.useful,      44 ),
    "Recycle Charm":        (ItemType.Charm,    ItemClassification.useful,      45,     ["Clunk"]),
    "Scorchberry Charm":    (ItemType.Charm,    ItemClassification.useful,      46 ),
    "Scrap Charm":          (ItemType.Charm,    ItemClassification.useful,      47 ),
    "Shade Slug":           (ItemType.Charm,    ItemClassification.useful,      48 ),
    "Shield Charm":         (ItemType.Charm,    ItemClassification.useful,      49,     ["Snow"]),
    "Shroom Charm":         (ItemType.Charm,    ItemClassification.useful,      50,     ["Snow"]),
    "Snowball Charm":       (ItemType.Charm,    ItemClassification.useful,      51 ),
    "Spark Charm":          (ItemType.Charm,    ItemClassification.useful,      52 ),
    "Spice Charm":          (ItemType.Charm,    ItemClassification.useful,      53,     ["Snow"]),
    "Squid Charm":          (ItemType.Charm,    ItemClassification.useful,      54,     ["Clunk"]),
    "Strawberry Charm":     (ItemType.Charm,    ItemClassification.useful,      55 ),
    "Sun Charm":            (ItemType.Charm,    ItemClassification.useful,      56 ),
    "Sunglass Charm":       (ItemType.Charm,    ItemClassification.useful,      57 ),
    "Tiger Charm":          (ItemType.Charm,    ItemClassification.useful,      58,     ["Shade"]),
    "Truffle Charm":        (ItemType.Charm,    ItemClassification.useful,      59,     ["Snow"]),
    "Zoomlin Charm":        (ItemType.Charm,    ItemClassification.useful,      60 ),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
unit_list = {
    "Snoof":                (ItemType.Unit,     ItemClassification.useful,      0  ),
    "Booshu":               (ItemType.Unit,     ItemClassification.useful,      1  ),
    "Loki":                 (ItemType.Unit,     ItemClassification.useful,      2  ),
    "Sneezle":              (ItemType.Unit,     ItemClassification.useful,      3  ),
    "Spike":                (ItemType.Unit,     ItemClassification.useful,      4  ),
    "Binku":                (ItemType.Unit,     ItemClassification.useful,      5  ),
    "Lil' Gazi":            (ItemType.Unit,     ItemClassification.useful,      6  ),
    "Alloy":                (ItemType.Unit,     ItemClassification.useful,      7 ,     ["Clunk"]),
    "Berry Sis":            (ItemType.Unit,     ItemClassification.useful,      8 ,     ["Shade"]),
    "Big Berry":            (ItemType.Unit,     ItemClassification.useful,      9  ),
    "Biji":                 (ItemType.Unit,     ItemClassification.useful,      10,     ["Clunk"]),
    "Blunky":               (ItemType.Unit,     ItemClassification.useful,      11 ),
    "Bombom":               (ItemType.Unit,     ItemClassification.useful,      12 ),
    "Bonnie":               (ItemType.Unit,     ItemClassification.useful,      13 ),
    "Chikichi":             (ItemType.Unit,     ItemClassification.useful,      14,     ["Shade"]),
    "Chompom":              (ItemType.Unit,     ItemClassification.useful,      15,     ["Snow"]),
    "Devicro":              (ItemType.Unit,     ItemClassification.useful,      16,     ["Shade"]),
    "Dimona":               (ItemType.Unit,     ItemClassification.useful,      17 ),
    "Egg":                  (ItemType.Unit,     ItemClassification.useful,      18,     ["Shade"]),
    "Firefist":             (ItemType.Unit,     ItemClassification.useful,      19,     ["Snow"]),
    "Fizzle":               (ItemType.Unit,     ItemClassification.useful,      20,     ["Clunk"]),
    "Folby":                (ItemType.Unit,     ItemClassification.useful,      21,     ["Clunk"]),
    "Foxee":                (ItemType.Unit,     ItemClassification.useful,      22 ),
    "Fulbert":              (ItemType.Unit,     ItemClassification.useful,      23,     ["Clunk"]),
    "Fungun":               (ItemType.Unit,     ItemClassification.useful,      24,     ["Clunk"]),
    "Gojiber":              (ItemType.Unit,     ItemClassification.useful,      25 ),
    "Groff":                (ItemType.Unit,     ItemClassification.useful,      26 ),
    "Hazevlazer":           (ItemType.Unit,     ItemClassification.useful,      27 ),
    "Jumbo":                (ItemType.Unit,     ItemClassification.useful,      28 ),
    "Kernel":               (ItemType.Unit,     ItemClassification.useful,      29,     ["Snow"]),
    "Knuckles":             (ItemType.Unit,     ItemClassification.useful,      30,     ["Clunk"]),
    "Kreggo":               (ItemType.Unit,     ItemClassification.useful,      31,     ["Clunk"]),
    "Lil' Berry":           (ItemType.Unit,     ItemClassification.useful,      32,     ["Snow"]),
    "Lupa":                 (ItemType.Unit,     ItemClassification.useful,      33 ),
    "Mama Tinkerson":       (ItemType.Unit,     ItemClassification.useful,      34,     ["Clunk"]),
    "Mini Mika":            (ItemType.Unit,     ItemClassification.useful,      35,     ["Clunk"]),
    "Monch":                (ItemType.Unit,     ItemClassification.useful,      36,     ["Shade"]),
    "Naked Gnome":          (ItemType.Unit,     ItemClassification.useful,      37 ),
    "Needle":               (ItemType.Unit,     ItemClassification.useful,      38,     ["Clunk"]),
    "Nom & Stompy":         (ItemType.Unit,     ItemClassification.useful,      39,     ["Clunk"]),
    "Nova":                 (ItemType.Unit,     ItemClassification.useful,      40 ),
    "Pimento":              (ItemType.Unit,     ItemClassification.useful,      41,     ["Snow"]),
    "Pootie":               (ItemType.Unit,     ItemClassification.useful,      42,     ["Snow"]),
    "Pyra":                 (ItemType.Unit,     ItemClassification.useful,      43,     ["Snow"]),
    "Roibos":               (ItemType.Unit,     ItemClassification.useful,      44 ),
    "Scaven":               (ItemType.Unit,     ItemClassification.useful,      45,     ["Clunk"]),
    "Shelly":               (ItemType.Unit,     ItemClassification.useful,      46,     ["Snow"]),
    "Shen":                 (ItemType.Unit,     ItemClassification.useful,      47,     ["Shade"]),
    "Snobble":              (ItemType.Unit,     ItemClassification.useful,      48 ),
    "Snoffel":              (ItemType.Unit,     ItemClassification.useful,      49 ),
    "Splinter":             (ItemType.Unit,     ItemClassification.useful,      50,     ["Shade"]),
    "Spoof":                (ItemType.Unit,     ItemClassification.useful,      51,     ["Shade"]),
    "Taiga":                (ItemType.Unit,     ItemClassification.useful,      52,     ["Shade"]),
    "The Baker":            (ItemType.Unit,     ItemClassification.useful,      53,     ["Shade"]),
    "Tinkerson Jr.":        (ItemType.Unit,     ItemClassification.useful,      54,     ["Clunk"]),
    "Tiny Tyko":            (ItemType.Unit,     ItemClassification.useful,      55,     ["Snow"]),
    "Toaster":              (ItemType.Unit,     ItemClassification.useful,      56,     ["Clunk"]),
    "Tusk":                 (ItemType.Unit,     ItemClassification.useful,      57,     ["Shade"]),
    "Van Jun":              (ItemType.Unit,     ItemClassification.useful,      58,     ["Shade"]),
    "Vesta":                (ItemType.Unit,     ItemClassification.useful,      59,     ["Shade"]),
    "Wallop":               (ItemType.Unit,     ItemClassification.useful,      60,     ["Snow"]),
    "Wort":                 (ItemType.Unit,     ItemClassification.useful,      61,     ["Snow"]),
    "Yuki":                 (ItemType.Unit,     ItemClassification.useful,      62,     ["Snow"]),
    "Zula":                 (ItemType.Unit,     ItemClassification.useful,      63,     ["Shade"]),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
clunker_list = {
    "Bitebox":              (ItemType.Item,     ItemClassification.useful,      0  ),
    "Bling Bank":           (ItemType.Item,     ItemClassification.useful,      1  ),
    "Blundertank":          (ItemType.Item,     ItemClassification.useful,      2 ,     ["Clunk"]),
    "Bombarder":            (ItemType.Item,     ItemClassification.useful,      3 ,     ["Clunk"]),
    "Fungo Blaster":        (ItemType.Item,     ItemClassification.useful,      4 ,     ["Snow"]),
    "Gachapomper":          (ItemType.Item,     ItemClassification.useful,      5 ,     ["Clunk"]),
    "Haze Balloon":         (ItemType.Item,     ItemClassification.useful,      6 ,     ["Clunk"]),
    "Heartforge":           (ItemType.Item,     ItemClassification.useful,      7 ,     ["Snow"]),
    "Heartmist Station":    (ItemType.Item,     ItemClassification.useful,      8  ),
    "I.C.G.M":              (ItemType.Item,     ItemClassification.useful,      9 ,     ["Clunk"]),
    "Junkhead":             (ItemType.Item,     ItemClassification.useful,      10,     ["Clunk", "Starter"]),
    "Kobonker":             (ItemType.Item,     ItemClassification.useful,      11,     ["Snow"]),
    "Krono":                (ItemType.Item,     ItemClassification.useful,      12 ),
    "Mega Mimik":           (ItemType.Item,     ItemClassification.useful,      13 ),
    "Mimik":                (ItemType.Item,     ItemClassification.useful,      14 ),
    "Mobile Campfire":      (ItemType.Item,     ItemClassification.useful,      15,     ["Snow"]),
    "Moko Totem":           (ItemType.Item,     ItemClassification.useful,      16,     ["Snow"]),
    "Pepper Flag":          (ItemType.Item,     ItemClassification.useful,      17,     ["Snow"]),
    "Plinker":              (ItemType.Item,     ItemClassification.useful,      18,     ["Clunk"]),
    "Portable Workbench":   (ItemType.Item,     ItemClassification.useful,      19,     ["Clunk"]),
    "Shroominator":         (ItemType.Item,     ItemClassification.useful,      20,     ["Snow"]),
    "Shroomine":            (ItemType.Item,     ItemClassification.useful,      21,     ["Snow"]),
    "Spice Sparklers":      (ItemType.Item,     ItemClassification.useful,      22,     ["Snow"]),
    "Sunglass Chime":       (ItemType.Item,     ItemClassification.useful,      23,     ["Clunk"]),
    "Tootordion":           (ItemType.Item,     ItemClassification.useful,      24,     ["Clunk"]),
    "Totem of the Goat":    (ItemType.Item,     ItemClassification.useful,      25 ),
    "Woodhead":             (ItemType.Item,     ItemClassification.useful,      26,     ["Snow", "Starter"]),
    "Zoomlin Nest":         (ItemType.Item,     ItemClassification.useful,      27 ),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
cards_list = {
    "Azul Battle Axe":      (ItemType.Item,     ItemClassification.useful,      28,     ["Shade"]),
    "Azul Candle":          (ItemType.Item,     ItemClassification.useful,      29,     ["Shade"]),
    "Azul Skull":           (ItemType.Item,     ItemClassification.useful,      30,     ["Shade"]),
    "B.I.N.K":              (ItemType.Item,     ItemClassification.useful,      31,     ["Clunk"]),
    "Beepop Mask":          (ItemType.Item,     ItemClassification.useful,      32,     ["Shade"]),
    "Berry Basket":         (ItemType.Item,     ItemClassification.useful,      33 ),
    "Berry Bell":           (ItemType.Item,     ItemClassification.useful,      34,     ["Shade", "Starter"]),
    "Berry Blade":          (ItemType.Item,     ItemClassification.useful,      35 ),
    "Blank Mask":           (ItemType.Item,     ItemClassification.useful,      36,     ["Shade"]),
    "Blaze Bom":            (ItemType.Item,     ItemClassification.useful,      37,     ["Clunk"]),
    "Blaze Tea":            (ItemType.Item,     ItemClassification.useful,      38 ),
    "Blizzard Bottle":      (ItemType.Item,     ItemClassification.useful,      39,     ["Starter"]),
    "Bom Barrel":           (ItemType.Item,     ItemClassification.useful,      40,     ["Clunk"]),
    "Bonescraper":          (ItemType.Item,     ItemClassification.useful,      41,     ["Shade"]),
    "Broken Vase":          (ItemType.Item,     ItemClassification.progression, 42 ),
    "Clockwork Bom":        (ItemType.Item,     ItemClassification.useful,      43,     ["Clunk"]),
    "Demonheart":           (ItemType.Item,     ItemClassification.useful,      44 ),
    "Dragon Pepper":        (ItemType.Item,     ItemClassification.useful,      45,     ["Snow"]),
    "Fallow Mask":          (ItemType.Item,     ItemClassification.useful,      46,     ["Shade"]),
    "Flamewater":           (ItemType.Item,     ItemClassification.useful,      47,     ["Snow", "Starter"]),
    "Flask of Ink":         (ItemType.Item,     ItemClassification.useful,      48,     ["Clunk", "Starter"]),
    "Foggy Brew":           (ItemType.Item,     ItemClassification.useful,      49,     ["Clunk"]),
    "Forging Stove":        (ItemType.Item,     ItemClassification.useful,      50,     ["Clunk"]),
    "Frenzy Wrench":        (ItemType.Item,     ItemClassification.useful,      51,     ["Clunk"]),
    "Frost Bell":           (ItemType.Item,     ItemClassification.useful,      52 ),
    "Frostbite Shard":      (ItemType.Item,     ItemClassification.useful,      53,     ["Clunk"]),
    "Frostbloom":           (ItemType.Item,     ItemClassification.useful,      54 ),
    "Gigi's Cookie Box":    (ItemType.Item,     ItemClassification.useful,      55,     ["Clunk"]),
    "Gigi's Gizmo":         (ItemType.Item,     ItemClassification.useful,      56,     ["Clunk"]),
    "Grabber":              (ItemType.Item,     ItemClassification.useful,      57 ),
    "Haze Keg":             (ItemType.Item,     ItemClassification.useful,      58,     ["Clunk"]),
    "Hongo's Hammer":       (ItemType.Item,     ItemClassification.useful,      59,     ["Snow"]),
    "Ice Dice":             (ItemType.Item,     ItemClassification.useful,      60 ),
    "Junjun Mask":          (ItemType.Item,     ItemClassification.useful,      61,     ["Shade", "Starter"]),
    "Leech Mask":           (ItemType.Item,     ItemClassification.useful,      62,     ["Shade"]),
    "Lumin Goop":           (ItemType.Item,     ItemClassification.progression, 63 ),
    "Lumin Lantern":        (ItemType.Item,     ItemClassification.useful,      64,     ["Clunk"]),
    "Magma Booster":        (ItemType.Item,     ItemClassification.useful,      65,     ["Clunk"]),
    "Mini Muncher":         (ItemType.Item,     ItemClassification.useful,      66,     ["Clunk"]),
    "Molten Dip":           (ItemType.Item,     ItemClassification.useful,      67 ),
    "Noomlin Biscuit":      (ItemType.Item,     ItemClassification.useful,      68 ),
    "Nutshell Cake":        (ItemType.Item,     ItemClassification.useful,      69,     ["Snow"]), # nice
    "Peppereaper":          (ItemType.Item,     ItemClassification.useful,      70,     ["Snow"]),
    "Peppering":            (ItemType.Item,     ItemClassification.useful,      71,     ["Snow"]),
    "Pinkberry Juice":      (ItemType.Item,     ItemClassification.useful,      72 ),
    "Pom Mask":             (ItemType.Item,     ItemClassification.useful,      73,     ["Shade"]),
    "Pombomb":              (ItemType.Item,     ItemClassification.useful,      74 ),
    "Proto-Stomper":        (ItemType.Item,     ItemClassification.useful,      75,     ["Clunk"]),
    "Scrap Pile":           (ItemType.Item,     ItemClassification.useful,      76,     ["Snow"]),
    "Shade Clay":           (ItemType.Item,     ItemClassification.useful,      77,     ["Shade"]),
    "Shade Wisp":           (ItemType.Item,     ItemClassification.useful,      78,     ["Shade"]),
    "Sheepopper Mask":      (ItemType.Item,     ItemClassification.useful,      79,     ["Shade"]),
    "Shell Shield":         (ItemType.Item,     ItemClassification.useful,      80,     ["Snow"]),
    "Shellbo":              (ItemType.Item,     ItemClassification.useful,      81,     ["Snow"]),
    "Skull Muffin":         (ItemType.Item,     ItemClassification.useful,      82,     ["Shade"]),
    "Skullmist Tea":        (ItemType.Item,     ItemClassification.useful,      83,     ["Shade"]),
    "Slapcrackers":         (ItemType.Item,     ItemClassification.useful,      84 ),
    "Snow Stick":           (ItemType.Item,     ItemClassification.useful,      85,     ["Snow", "Starter"]),
    "Snowcake":             (ItemType.Item,     ItemClassification.useful,      86 ),
    "Snowzooka":            (ItemType.Item,     ItemClassification.useful,      87,     ["Clunk", "Starter"]),
    "Snuffer Mask":         (ItemType.Item,     ItemClassification.useful,      88,     ["Shade"]),
    "Soulbound Skulls":     (ItemType.Item,     ItemClassification.useful,      89,     ["Shade"]),
    "Spice Stones":         (ItemType.Item,     ItemClassification.useful,      90,     ["Snow"]),
    "Spore Pack":           (ItemType.Item,     ItemClassification.useful,      91,     ["Snow"]),
    "Storm Globe":          (ItemType.Item,     ItemClassification.useful,      92 ),
    "Stormbear Spirit":     (ItemType.Item,     ItemClassification.useful,      93,     ["Snow"]),
    "Sun Rod":              (ItemType.Item,     ItemClassification.useful,      94,     ["Snow", "Starter"]),
    "Sunburst Tootoo":      (ItemType.Item,     ItemClassification.useful,      95,     ["Shade", "Starter"]),
    "Suncream":             (ItemType.Item,     ItemClassification.useful,      96,     ["Clunk"]),
    "Sunlight Drum":        (ItemType.Item,     ItemClassification.useful,      97 ),
    "Sunsong Box":          (ItemType.Item,     ItemClassification.useful,      98,     ["Clunk", "Starter"]),
    "Supersnower":          (ItemType.Item,     ItemClassification.useful,      99,     ["Clunk"]),
    "The Lumin Vase":       (ItemType.Item,     ItemClassification.progression, 100),
    "Tiger Skull":          (ItemType.Item,     ItemClassification.useful,      101,    ["Shade"]),
    "Tigris Mask":          (ItemType.Item,     ItemClassification.useful,      102,    ["Shade"]),
    "Yeti Skull":           (ItemType.Item,     ItemClassification.useful,      103,    ["Shade"]),
    "Zoomlin Wafers":       (ItemType.Item,     ItemClassification.useful,      104),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
sun_bell_list = {
    "Sun Bell of Hands":    (ItemType.Bell,     ItemClassification.useful,      0  ),
    "Sun Bell of Fellowship":(ItemType.Bell,    ItemClassification.useful,      1  ),
    "Sun Bell of the Bell": (ItemType.Bell,     ItemClassification.useful,      2  ),
    "Sun Bell of Health":   (ItemType.Bell,     ItemClassification.useful,      3  ),
    "Sun Bell of Time":     (ItemType.Bell,     ItemClassification.useful,      4  ),
    "Sun Bell of Recall":   (ItemType.Bell,     ItemClassification.useful,      5  ),
    "Sun Bell of Charge":   (ItemType.Bell,     ItemClassification.useful,      6  ),
    "Noomlin Sun Bell":     (ItemType.Bell,     ItemClassification.useful,      7  ),
    "Sun Bell of Strength": (ItemType.Bell,     ItemClassification.useful,      8  ),
    "Breakfast Sun Bell":   (ItemType.Bell,     ItemClassification.useful,      9  ),
    "Infinity Sun Bell":    (ItemType.Bell,     ItemClassification.useful,      10 ),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
storm_bell_list = {
    "Blingsnail Bell":      (ItemType.Bell,     ItemClassification.progression, 11,     ["Power1"]),
    "Bell of Death":        (ItemType.Bell,     ItemClassification.progression, 12,     ["Power1"]),
    "Titan Bell":           (ItemType.Bell,     ItemClassification.progression, 13,     ["Power2"]),
    "Frosthand Bell":       (ItemType.Bell,     ItemClassification.progression, 14,     ["Power1"]),
    "Gunk Bell":            (ItemType.Bell,     ItemClassification.progression, 15,     ["Power1"]),
    "Icebourne Bell":       (ItemType.Bell,     ItemClassification.progression, 16,     ["Power2"]),
    "Horde Bell":           (ItemType.Bell,     ItemClassification.progression, 17,     ["Power2"]),
    "Gloom Bell":           (ItemType.Bell,     ItemClassification.progression, 18,     ["Power1"]),
    "Frostbourne Bell":     (ItemType.Bell,     ItemClassification.progression, 19,     ["Power2"]),
    "Gobbler Bell":         (ItemType.Bell,     ItemClassification.progression, 20,     ["Power2"]),
    "Tyrant Bell":          (ItemType.Bell,     ItemClassification.progression, 21,     ["Power2"]),
    "Dread Bell":           (ItemType.Bell,     ItemClassification.progression, 22,     ["Power3"]),
    "Blood Bell":           (ItemType.Bell,     ItemClassification.progression, 23,     ["Power2"]),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
voyage_bell_list = {
    "Battle Bell":          (ItemType.Bell,     ItemClassification.useful,      24 ),
    "Blingsack Bell":       (ItemType.Bell,     ItemClassification.useful,      25 ),
    "Bombskull Bell":       (ItemType.Bell,     ItemClassification.useful,      26 ),
    "Broken Bell":          (ItemType.Bell,     ItemClassification.useful,      27 ),
    "Fog Bell":             (ItemType.Bell,     ItemClassification.useful,      28 ),
    "Frenzy Bell":          (ItemType.Bell,     ItemClassification.useful,      29 ),
    "Frozen Heart Bell":    (ItemType.Bell,     ItemClassification.useful,      30 ),
    "Goat Bell":            (ItemType.Bell,     ItemClassification.useful,      31 ),
    "Gold Blade Bell":      (ItemType.Bell,     ItemClassification.useful,      32 ),
    "Heart Bell":           (ItemType.Bell,     ItemClassification.useful,      33 ),
    "Lumin Bell":           (ItemType.Bell,     ItemClassification.useful,      34 ),
    "Party Bell":           (ItemType.Bell,     ItemClassification.useful,      35 ),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
map_event_list = {
    "Gnome Traveller":      (ItemType.MapEvent, ItemClassification.useful,      0  ),
    "Shade Sculptor":       (ItemType.MapEvent, ItemClassification.useful,      1  ),
    "Charm Merchant":       (ItemType.MapEvent, ItemClassification.useful,      2  ),
    "Injured Companion":    (ItemType.MapEvent, ItemClassification.useful,      3  ),
    "Muncher":              (ItemType.MapEvent, ItemClassification.useful,      4  ),
    "Blingsnail Cave":      (ItemType.MapEvent, ItemClassification.useful,      5  ),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
tribe_list = {
    "Shademancers Tribe":   (ItemType.Tribe,    ItemClassification.progression, 0  ),
    "Clunkmasters Tribe":   (ItemType.Tribe,    ItemClassification.progression, 0  ),
}

#   Name                    (Item Type,         Progression Level,              LocalID Extra Tags)
trap_boon_list = {
    "Berry Basket Boon":    (ItemType.TrapBoon, ItemClassification.filler,      0  ),
    "Spicy Boon":           (ItemType.TrapBoon, ItemClassification.filler,      1  ),
    "Snowy Boon":           (ItemType.TrapBoon, ItemClassification.filler,      2  ),
    "Speed Boon":           (ItemType.TrapBoon, ItemClassification.filler,      3  ),
    "Bling Bling Boon":     (ItemType.TrapBoon, ItemClassification.filler,      4  ),
    "Sun Smite Boon":       (ItemType.TrapBoon, ItemClassification.filler,      5  ),

    "Bombard Trap":         (ItemType.TrapBoon, ItemClassification.filler,      6  ),
    "Hoghead Trap":         (ItemType.TrapBoon, ItemClassification.filler,      7  ),
    "Gunk Bomb Trap":       (ItemType.TrapBoon, ItemClassification.filler,      8  ),
    "Ice Wall Trap":        (ItemType.TrapBoon, ItemClassification.filler,      9  ),
    "Ink Blot Trap":        (ItemType.TrapBoon, ItemClassification.filler,      10 ),
    "Goofy Gobbler Trap":   (ItemType.TrapBoon, ItemClassification.filler,      12 ),

    "Support Death Event":  (ItemType.TrapBoon, ItemClassification.filler,      13 ),
    "Throwing Shade Event": (ItemType.TrapBoon, ItemClassification.filler,      14 ),
    "Cursed Crown Event":   (ItemType.TrapBoon, ItemClassification.filler,      14 ),
}

full_item_list = {
    **building_list,
    **charm_list,
    **unit_list,
    **clunker_list,
    **cards_list,
    **sun_bell_list,
    **storm_bell_list,
    **voyage_bell_list,
    **map_event_list,
    **tribe_list,
    **trap_boon_list
}