

#   Name                        Dynamic Size
reward_pools = {
    "General Companion":        (True),
    "Snowdweller Companion":    (True),
    "Shademancer Companion":    (True),
    "Clunkmaster Companion":    (True),
    "General Item":             (True),
    "Snowdweller Item":         (True),
    "Shademancer Item":         (True),
    "Clunkmaster Item":         (True),
    "General Charm":            (True),
    "Snowdweller Charm":        (True),
    "Shademancer Charm":        (True),
    "Clunkmaster Charm":        (True),
    "Boss Fight Reward":        (True)
}

buildings = {
    "Build Frostoscope":        (False),
    "Build Hot Spring":         (False),
    "Build Icebreaker Cabin":   (False),
    "Build Inventor Hut":       (False),
    "Build Pet House":          (False),
    "Build Tribe Hall":         (False)
}

building_challenges = {
    "Shademancer Unlock":       (False),
    "Clunkmasters Unlock":      (False),
    "Pet House Unlock":         (False),
    "Inventors Hut Unlock":     (False),
    "Icebreaker Cabin Unlock":  (False),
    "Hot Spring Unlock":        (False)
}

idols = {
    "Balloonist Idol":          (False),
    "Beastmaster Idol":         (False),
    "Berry Good Idol":          (False),
    "Best Friends Idol":        (False),
    "Big Hitter Idol":          (False),
    "Bigger Hitter Idol":       (False),
    "Charmless Idol":           (False),
    "Clunkmaster Idol":         (False),
    "Feed The Beast Idol":      (False),
    "Gnome Friend Idol":        (False),
    "Gnomebringer Idol":        (False),
    "High Roller Idol":         (False),
    "Hoarder Idol":             (False),
    "Icemaster Idol":           (False),
    "Lone Survivor Idol":       (False),
    "Long Live The King Idol":  (False),
    "Minimalist Idol":          (False),
    "One Punch Idol":           (False),
    "Rampage Idol":             (False),
    "Ritual Idol":              (False),
    "Shademancer Idol":         (False),
    "Snowball Fight Idol":      (False),
    "Snowdweller Idol":         (False),
    "Sunbringer Idol":          (False),
    "Tough Nut Idol":           (False),
    "Toxic Idol":               (False),
    "Undefeated Idol":          (False)
}

enemy_kills = {
    "Kill Baby Snowbo":    (False),
    "Kill Beeberry":    (False),
    "Kill Berry Witch":    (False),
    "Kill Bigfoot":    (False),
    "Kill Blaze Beetles":    (False),
    "Kill Bulbhead":    (False),
    "Kill Burster":    (False),
    "Kill Chungoon":    (False),
    "Kill Conker":    (False),
    "Kill Dungrok":    (False),
    "Kill Earth Berry":    (False),
    "Kill Frostinger":    (False),
    "Kill Gobbler":    (False),
    "Kill Gobling":    (False),
    "Kill Gogong":    (False),
    "Kill Gok":    (False),
    "Kill Grink":    (False),
    "Kill Grizzle":    (False),
    "Kill Grog":    (False),
    "Kill Gromble":    (False),
    "Kill Grouchy":    (False),
    "Kill Grumps":    (False),
    "Kill Gunk Gobbler":    (False),
    "Kill Gunkback":    (False),
    "Kill Hog":    (False),
    "Kill Jab Joat":    (False),
    "Kill Krab":    (False),
    "Kill Kraken":    (False),
    "Kill Krawler":    (False),
    "Kill Lump":    (False),
    "Kill Makoko":    (False),
    "Kill Marrow":    (False),
    "Kill Minimoko":    (False),
    "Kill Naked Gnome":    (False),
    "Kill Octako":    (False),
    "Kill Ooba Bear":    (False),
    "Kill Paw Paw":    (False),
    "Kill Pecan":    (False),
    "Kill Pengoon":    (False),
    "Kill Pepper Witch":    (False),
    "Kill Plum":    (False),
    "Kill Popshroom":    (False),
    "Kill Porkypine":    (False),
    "Kill Prickle":    (False),
    "Kill Puffball":    (False),
    "Kill Pygmy":    (False),
    "Kill Rockhog":    (False),
    "Kill Shell Witch":    (False),
    "Kill Shroom Gobbler":    (False),
    "Kill Shrootles":    (False),
    "Kill Smog":    (False),
    "Kill Snow Gobbler":    (False),
    "Kill Snowbirb":    (False),
    "Kill Snowbo":    (False),
    "Kill Spuncher":    (False),
    "Kill Tentickle":    (False),
    "Kill Waddlegoons":    (False),
    "Kill Warthog":    (False),
    "Kill Wild Snoolf":    (False),
    "Kill Willow":    (False),
    "Kill Winter Worm":    (False),
    "Kill Woolly Drek":    (False),
}

boss_kills = {

}